version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14.17.0
    working_directory: ~/repo

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

  lint:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run linter
          command: npm run lint

  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm run test

  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Build application
          command: npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install